---
# Dependencies
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Record HK
tagline: 'hk_protest'
description: Reclaim Hong Kong, Revolution of Our Times
timezone: Europe/Berlin
baseurl: '/revo_hk'
plugins:
  - jekyll-maps

google_maps_javascript_api_key: AIzaSyD-SUCtVyrwJCVRczdA8oWdTMX_89SyGw8